import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
padding = { x = 4, y = 16 }
option_as_alt = "Both"
dynamic_title = false
title = ""

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
size = 18.0
